application: readability-api
version: default
runtime: python
api_version: 1

handlers:
- url: /admin.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin
- url: /_ah/queue/deferred
  script: $PYTHON_LIB/google/appengine/ext/deferred/deferred.py
  login: admin
- url: /.*
  script: main.py
