application: readability-api
version: default
runtime: python
api_version: 1

default_expiration: 4d

builtins:
- appstats: on

handlers:
- url: /(embedded_media\.png|favicon\.ico|robots\.txt)
  static_files: static/\1
  upload: static/(.*)

- url: /admin.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin
  secure: always

- url: /_ah/queue/deferred
  script: $PYTHON_LIB/google/appengine/ext/deferred/handler.py
  login: admin

- url: /crons/.*
  script: crons.py
  login: admin

- url: /.*
  script: main.py
