application: readability-api-hrd
version: 1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: 4d

builtins:
- appstats: on
- deferred: on

handlers:
- url: /(embedded_media\.png|favicon\.ico|robots\.txt)
  static_files: static/\1
  upload: static/(.*)

- url: /_ah/admin.*
  script: google.appengine.ext.admin.application
  login: admin
  secure: always

- url: /crons/.*
  script: crons.application
  login: admin

- url: /.*
  script: main.application
