# Generated by Django 3.1.7 on 2021-03-20 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(default=None)),
                ('title', models.TextField(default=None)),
                ('link', models.TextField(default=None)),
                ('last_fetch_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default=None)),
                ('link', models.TextField(default=None)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(default=None)),
                ('original_content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='readability.feed')),
            ],
        ),
    ]
