# Generated by Django 3.1.7 on 2021-03-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readability', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='tags',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='feed',
            name='fetch_interval_seconds',
            field=models.IntegerField(default=14400),
        ),
    ]
